[project]
name = "sudoku"
version = "0.1.0"
description = "Python modules kata"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-sugar>=1.1.1",
]
lint = [
    "ruff>=0.14.4",
]
